-- ===================================================================
-- TEMPORARY DEMO SEED - Meridian Commercial Bank
-- Tenant: intertec-systems-0c600f88
-- Every row uses id >= 9000 and created_by='demo-seed'.
-- Remove with teardown-intertec.sql
-- ===================================================================

USE autoops_core;

INSERT INTO projects (id, tenant_id, name, description, status, created_by) VALUES
(9001, 'intertec-systems-0c600f88', 'Retail Banking Operations',
 'Core banking batch, payments reconciliation, cards settlement, financial crime and regulatory reporting.',
 'ACTIVE', 'demo-seed');

INSERT INTO jobs (id, tenant_id, project_id, name, job_group, description, definition, step_count, schedule, schedule_timezone, enabled, requires_approval, next_run_at, created_by) VALUES
(9101,'intertec-systems-0c600f88',9001,'Core Banking EOD Batch Close','Core Banking','Cuts off the business date, runs interest accrual, posts GL entries and reopens the ledger.','{"steps":[{"type":"script","label":"Freeze business date"},{"type":"script","label":"Interest accrual"},{"type":"script","label":"GL posting"},{"type":"script","label":"Balance validation"},{"type":"script","label":"Reopen ledger"},{"type":"notify","label":"Notify ops"},{"type":"script","label":"Archive"},{"type":"script","label":"Checkpoint"},{"type":"script","label":"Release downstream"}]}',9,'30 23 * * 1-5','Asia/Kolkata',1,1,'2026-08-04 18:00:00','demo-seed'),
(9102,'intertec-systems-0c600f88',9001,'SWIFT MT940 Statement Ingestion','Payments','Pulls MT940/MT942 from the SWIFT gateway and loads reconciliation staging.','{"steps":[{"type":"script","label":"Connect gateway"},{"type":"script","label":"Fetch statements"},{"type":"script","label":"Checksum validate"},{"type":"script","label":"Parse MT940"},{"type":"script","label":"Load staging"},{"type":"notify","label":"Notify"}]}',6,'0 */2 * * *','Asia/Kolkata',1,0,'2026-08-04 08:00:00','demo-seed'),
(9103,'intertec-systems-0c600f88',9001,'NEFT / RTGS Outward Settlement Reconciliation','Payments','Three-way match: payment hub, nostro statement, central bank settlement file.','{"steps":[{"type":"script","label":"Load hub extract"},{"type":"script","label":"Load nostro statement"},{"type":"script","label":"Load CB settlement"},{"type":"script","label":"Three-way match"},{"type":"script","label":"Classify breaks"},{"type":"script","label":"Raise exceptions"},{"type":"notify","label":"Notify desk"}]}',7,'15 * * * *','Asia/Kolkata',1,0,'2026-08-04 07:15:00','demo-seed'),
(9104,'intertec-systems-0c600f88',9001,'Card Scheme Settlement File Import','Cards','Ingests Visa VSS and Mastercard IPM clearing files and posts settlement positions.','{"steps":[{"type":"script","label":"Fetch VSS"},{"type":"script","label":"Fetch IPM"},{"type":"script","label":"Normalise interchange"},{"type":"script","label":"Validate totals"},{"type":"script","label":"Post to GL"},{"type":"script","label":"Reconcile"},{"type":"script","label":"Archive"},{"type":"notify","label":"Notify"}]}',8,'45 2 * * *','Asia/Kolkata',1,0,'2026-08-05 02:45:00','demo-seed'),
(9105,'intertec-systems-0c600f88',9001,'AML Transaction Screening Feed','Financial Crime','Streams cleared transactions into sanctions and behavioural screening.','{"steps":[{"type":"script","label":"Extract cleared txns"},{"type":"script","label":"Push to screening"},{"type":"script","label":"Poll alerts"},{"type":"script","label":"Load alert IDs"},{"type":"notify","label":"Notify fincrime"}]}',5,'*/15 * * * *','Asia/Kolkata',1,0,'2026-08-04 07:00:00','demo-seed'),
(9106,'intertec-systems-0c600f88',9001,'KYC Document Expiry Sweep','Compliance','Flags customers whose ID, address proof or risk review lapses within 30 days.','{"steps":[{"type":"script","label":"Scan documents"},{"type":"script","label":"Apply expiry rules"},{"type":"script","label":"Queue re-KYC"},{"type":"notify","label":"Notify branches"}]}',4,'0 5 * * *','Asia/Kolkata',1,0,'2026-08-05 05:00:00','demo-seed'),
(9107,'intertec-systems-0c600f88',9001,'ATM Cash Position Reconciliation','Channels','Reconciles switch dispense records against CIT replenishment across 1,240 terminals.','{"steps":[{"type":"script","label":"Pull switch records"},{"type":"script","label":"Pull CIT data"},{"type":"script","label":"Cassette counts"},{"type":"script","label":"Reconcile"},{"type":"script","label":"Raise shortages"},{"type":"notify","label":"Notify channels"}]}',6,'0 4 * * *','Asia/Kolkata',1,0,'2026-08-05 04:00:00','demo-seed'),
(9108,'intertec-systems-0c600f88',9001,'Regulatory Return Data Extract','Regulatory','Builds CRILC, SLR and CRR datasets from the closed ledger.','{"steps":[{"type":"script","label":"Verify ledger closed"},{"type":"script","label":"Extract CRILC"},{"type":"script","label":"Extract SLR"},{"type":"script","label":"Extract CRR"},{"type":"script","label":"Validate"},{"type":"script","label":"Handoff"},{"type":"notify","label":"Notify reporting"}]}',7,'0 2 1 * *','Asia/Kolkata',1,1,'2026-09-01 02:00:00','demo-seed'),
(9109,'intertec-systems-0c600f88',9001,'Customer e-Statement Generation','Customer','Renders and encrypts monthly statements for 2.1M retail accounts.','{"steps":[{"type":"script","label":"Select accounts"},{"type":"script","label":"Render PDFs"},{"type":"script","label":"Encrypt"},{"type":"script","label":"Queue delivery"},{"type":"notify","label":"Notify"}]}',5,'0 3 1 * *','Asia/Kolkata',1,0,'2026-09-01 03:00:00','demo-seed'),
(9110,'intertec-systems-0c600f88',9001,'DR Replication Verify','Platform','Confirms the core banking standby is inside its 5-minute RPO.','{"steps":[{"type":"script","label":"Check standby lag"},{"type":"script","label":"Verify log shipping"},{"type":"script","label":"Record RPO"},{"type":"notify","label":"Notify SRE"}]}',4,'0 */6 * * *','Asia/Kolkata',1,0,'2026-08-04 12:00:00','demo-seed'),
(9111,'intertec-systems-0c600f88',9001,'Dormant Account Classification','Core Banking','Applies inactivity rules and suppresses channel access pending re-activation.','{"steps":[{"type":"script","label":"Scan activity"},{"type":"script","label":"Apply rules"},{"type":"approval","label":"Ops sign-off"},{"type":"script","label":"Mark dormant"},{"type":"notify","label":"Notify"}]}',5,'0 6 * * 0','Asia/Kolkata',1,1,'2026-08-09 06:00:00','demo-seed'),
(9112,'intertec-systems-0c600f88',9001,'Nostro Balance Sweep','Treasury','Sweeps surplus correspondent balances to the concentration account.','{"steps":[{"type":"script","label":"Read balances"},{"type":"script","label":"Compute surplus"},{"type":"approval","label":"Treasury approval"},{"type":"script","label":"Execute sweep"},{"type":"script","label":"Confirm"},{"type":"notify","label":"Notify"}]}',6,'0 16 * * 1-5','Asia/Kolkata',0,1,NULL,'demo-seed');

INSERT INTO runs (id, tenant_id, project_id, target_type, target_id, target_name, status, trigger_type, triggered_by, step_total, step_completed, cancel_requested, log, error, started_at, finished_at, duration_ms) VALUES
(9401,'intertec-systems-0c600f88',9001,'JOB',9101,'Core Banking EOD Batch Close','SUCCEEDED','SCHEDULE','scheduler',9,9,0,'Business date rolled to 2026-08-04. 2,184,331 accounts accrued, GL balanced to zero variance.',NULL,'2026-08-03 18:00:11','2026-08-03 18:39:52',2381000),
(9402,'intertec-systems-0c600f88',9001,'JOB',9103,'NEFT / RTGS Outward Settlement Reconciliation','FAILED','SCHEDULE','scheduler',7,5,0,'Matching hub extract against nostro statement...','14 unmatched breaks totalling 2.41 Cr - correspondent statement arrived late','2026-08-04 06:15:00','2026-08-04 06:21:48',408000),
(9403,'intertec-systems-0c600f88',9001,'WORKFLOW',9202,'Payment Exception Repair','RUNNING','SCHEDULE','system',9,5,0,'9 of 14 breaks auto-repaired. 5 funding breaks awaiting payments desk sign-off.',NULL,'2026-08-04 06:41:12',NULL,NULL),
(9404,'intertec-systems-0c600f88',9001,'WORKFLOW',9203,'Card Fraud Alert Triage','SUCCEEDED','WEBHOOK','fraud-engine',8,8,0,'Card ending 4417 blocked at switch, chargeback case CB-88213 raised, customer notified. 71s alert-to-block.',NULL,'2026-08-04 06:52:03','2026-08-04 06:53:14',71000),
(9405,'intertec-systems-0c600f88',9001,'JOB',9107,'ATM Cash Position Reconciliation','SUCCEEDED','SCHEDULE','scheduler',6,6,0,'1,240 terminals reconciled. 3 shortages raised (42,500 total), CIT tickets created.',NULL,'2026-08-04 04:00:00','2026-08-04 04:08:31',511000),
(9406,'intertec-systems-0c600f88',9001,'JOB',9104,'Card Scheme Settlement File Import','SUCCEEDED','SCHEDULE','scheduler',8,8,0,'Visa VSS and Mastercard IPM ingested. Net settlement position 18.7 Cr posted to GL.',NULL,'2026-08-04 02:45:00','2026-08-04 03:00:12',912000),
(9407,'intertec-systems-0c600f88',9001,'WORKFLOW',9201,'Retail Account Onboarding','RUNNING','MANUAL','branch-4412',11,5,0,'Possible PEP name match - held for compliance review rather than auto-creating the account.',NULL,'2026-08-04 06:22:00',NULL,NULL),
(9408,'intertec-systems-0c600f88',9001,'WORKFLOW',9206,'Production Change Release','FAILED','MANUAL','release-manager',10,9,0,'Canary in region A breached the latency budget on balance-enquiry. Auto-rolled back in 94s, zero customer impact.','Error budget breach - rolled back','2026-08-03 19:15:00','2026-08-03 19:41:20',1580000),
(9409,'intertec-systems-0c600f88',9001,'WORKFLOW',9205,'Month-End Regulatory Reporting','SUCCEEDED','SCHEDULE','scheduler',9,9,0,'CRILC, SLR and CRR returns submitted 4 days ahead of deadline. Evidence pack archived.',NULL,'2026-08-01 02:00:00','2026-08-01 02:47:30',2850000),
(9410,'intertec-systems-0c600f88',9001,'JOB',9110,'DR Replication Verify','SUCCEEDED','SCHEDULE','scheduler',4,4,0,'Standby lag 41s - inside the 5-minute RPO. No log-shipping gaps.',NULL,'2026-08-04 06:00:00','2026-08-04 06:01:36',96000),
(9411,'intertec-systems-0c600f88',9001,'JOB',9102,'SWIFT MT940 Statement Ingestion','SUCCEEDED','SCHEDULE','scheduler',6,6,0,'42 statements ingested, checksums valid.',NULL,'2026-08-04 06:00:04','2026-08-04 06:03:08',184000),
(9412,'intertec-systems-0c600f88',9001,'JOB',9105,'AML Transaction Screening Feed','SUCCEEDED','SCHEDULE','scheduler',5,5,0,'18,402 transactions screened, 7 alerts raised for triage.',NULL,'2026-08-04 06:45:00','2026-08-04 06:46:02',62000);

USE autoops_workflow;

INSERT INTO workflows (id, tenant_id, project_id, name, definition, node_count, enabled, created_by) VALUES
(9201,'intertec-systems-0c600f88',9001,'Retail Account Onboarding','{"category":"Customer","nodes":[{"id":"n1","type":"trigger","label":"Application received","x":40,"y":200},{"id":"n2","type":"script","label":"Extract KYC documents","x":280,"y":200},{"id":"n3","type":"script","label":"Verify identity vs bureau","x":520,"y":200},{"id":"n4","type":"script","label":"Sanctions / PEP screening","x":760,"y":200},{"id":"n5","type":"script","label":"Risk category decision","x":1000,"y":200},{"id":"n6","type":"approval","label":"Manual review gate","x":1240,"y":120},{"id":"n7","type":"script","label":"Create customer in core","x":1480,"y":200},{"id":"n8","type":"script","label":"Open CASA account","x":1720,"y":200},{"id":"n9","type":"script","label":"Issue debit card","x":1960,"y":200},{"id":"n10","type":"notify","label":"Dispatch welcome kit","x":2200,"y":200},{"id":"n11","type":"notify","label":"Notify relationship manager","x":2440,"y":200}],"edges":[{"from":"n1","to":"n2"},{"from":"n2","to":"n3"},{"from":"n3","to":"n4"},{"from":"n4","to":"n5"},{"from":"n5","to":"n6"},{"from":"n6","to":"n7"},{"from":"n7","to":"n8"},{"from":"n8","to":"n9"},{"from":"n9","to":"n10"},{"from":"n10","to":"n11"}]}',11,1,'demo-seed'),
(9202,'intertec-systems-0c600f88',9001,'Payment Exception Repair','{"category":"Payments","nodes":[{"id":"n1","type":"trigger","label":"Poll reconciliation breaks","x":40,"y":200},{"id":"n2","type":"script","label":"Classify break reason","x":280,"y":200},{"id":"n3","type":"script","label":"Auto-repair BIC / IBAN","x":520,"y":120},{"id":"n4","type":"script","label":"Auto-repair remittance info","x":520,"y":280},{"id":"n5","type":"script","label":"Funding check vs nostro","x":760,"y":200},{"id":"n6","type":"approval","label":"Payments desk approval","x":1000,"y":200},{"id":"n7","type":"script","label":"Resubmit to payment hub","x":1240,"y":200},{"id":"n8","type":"script","label":"Update reconciliation","x":1480,"y":200},{"id":"n9","type":"notify","label":"Notify originating branch","x":1720,"y":200}],"edges":[{"from":"n1","to":"n2"},{"from":"n2","to":"n3"},{"from":"n2","to":"n4"},{"from":"n3","to":"n5"},{"from":"n4","to":"n5"},{"from":"n5","to":"n6"},{"from":"n6","to":"n7"},{"from":"n7","to":"n8"},{"from":"n8","to":"n9"}]}',9,1,'demo-seed'),
(9203,'intertec-systems-0c600f88',9001,'Card Fraud Alert Triage','{"category":"Financial Crime","nodes":[{"id":"n1","type":"webhook","label":"Fraud score event","x":40,"y":200},{"id":"n2","type":"script","label":"Enrich customer profile","x":280,"y":200},{"id":"n3","type":"script","label":"Threshold decision","x":520,"y":200},{"id":"n4","type":"script","label":"Block card at switch","x":760,"y":200},{"id":"n5","type":"script","label":"Raise chargeback case","x":1000,"y":200},{"id":"n6","type":"notify","label":"SMS / push customer","x":1240,"y":200},{"id":"n7","type":"script","label":"Create analyst task","x":1480,"y":200},{"id":"n8","type":"script","label":"Log to case management","x":1720,"y":200}],"edges":[{"from":"n1","to":"n2"},{"from":"n2","to":"n3"},{"from":"n3","to":"n4"},{"from":"n4","to":"n5"},{"from":"n5","to":"n6"},{"from":"n6","to":"n7"},{"from":"n7","to":"n8"}]}',8,1,'demo-seed'),
(9204,'intertec-systems-0c600f88',9001,'Unsecured Loan Credit Decisioning','{"category":"Lending","nodes":[{"id":"n1","type":"trigger","label":"Application intake","x":40,"y":200},{"id":"n2","type":"script","label":"Credit bureau pull","x":280,"y":200},{"id":"n3","type":"script","label":"Affordability check","x":520,"y":200},{"id":"n4","type":"script","label":"Policy rule evaluation","x":760,"y":200},{"id":"n5","type":"script","label":"Risk-based pricing","x":1000,"y":200},{"id":"n6","type":"script","label":"Delegated authority check","x":1240,"y":200},{"id":"n7","type":"approval","label":"Credit officer approval","x":1480,"y":200},{"id":"n8","type":"script","label":"Generate sanction letter","x":1720,"y":200},{"id":"n9","type":"script","label":"Disburse to account","x":1960,"y":200},{"id":"n10","type":"notify","label":"Notify customer","x":2200,"y":200}],"edges":[{"from":"n1","to":"n2"},{"from":"n2","to":"n3"},{"from":"n3","to":"n4"},{"from":"n4","to":"n5"},{"from":"n5","to":"n6"},{"from":"n6","to":"n7"},{"from":"n7","to":"n8"},{"from":"n8","to":"n9"},{"from":"n9","to":"n10"}]}',10,1,'demo-seed'),
(9205,'intertec-systems-0c600f88',9001,'Month-End Regulatory Reporting','{"category":"Regulatory","nodes":[{"id":"n1","type":"trigger","label":"Confirm ledger closed","x":40,"y":200},{"id":"n2","type":"script","label":"Run regulatory extract","x":280,"y":200},{"id":"n3","type":"script","label":"Schema validation","x":520,"y":200},{"id":"n4","type":"script","label":"Variance vs prior period","x":760,"y":200},{"id":"n5","type":"script","label":"Generate return pack","x":1000,"y":200},{"id":"n6","type":"approval","label":"Compliance review","x":1240,"y":200},{"id":"n7","type":"approval","label":"CFO sign-off gate","x":1480,"y":200},{"id":"n8","type":"script","label":"Submit to regulator","x":1720,"y":200},{"id":"n9","type":"script","label":"Archive evidence pack","x":1960,"y":200}],"edges":[{"from":"n1","to":"n2"},{"from":"n2","to":"n3"},{"from":"n3","to":"n4"},{"from":"n4","to":"n5"},{"from":"n5","to":"n6"},{"from":"n6","to":"n7"},{"from":"n7","to":"n8"},{"from":"n8","to":"n9"}]}',9,1,'demo-seed'),
(9206,'intertec-systems-0c600f88',9001,'Production Change Release','{"category":"Platform","nodes":[{"id":"n1","type":"trigger","label":"Change request intake","x":40,"y":200},{"id":"n2","type":"script","label":"Freeze-window check","x":280,"y":200},{"id":"n3","type":"approval","label":"CAB approval gate","x":520,"y":200},{"id":"n4","type":"script","label":"Pre-deploy backup","x":760,"y":200},{"id":"n5","type":"k8s","label":"Canary deploy region A","x":1000,"y":200},{"id":"n6","type":"script","label":"Synthetic transaction check","x":1240,"y":200},{"id":"n7","type":"script","label":"Error budget evaluation","x":1480,"y":200},{"id":"n8","type":"k8s","label":"Full rollout","x":1720,"y":120},{"id":"n9","type":"script","label":"Automated rollback","x":1720,"y":280},{"id":"n10","type":"notify","label":"Close change record","x":1960,"y":200}],"edges":[{"from":"n1","to":"n2"},{"from":"n2","to":"n3"},{"from":"n3","to":"n4"},{"from":"n4","to":"n5"},{"from":"n5","to":"n6"},{"from":"n6","to":"n7"},{"from":"n7","to":"n8"},{"from":"n7","to":"n9"},{"from":"n8","to":"n10"},{"from":"n9","to":"n10"}]}',10,1,'demo-seed'),
(9207,'intertec-systems-0c600f88',9001,'Quarterly DR Failover Drill','{"category":"Platform","nodes":[{"id":"n1","type":"trigger","label":"Announce drill window","x":40,"y":200},{"id":"n2","type":"script","label":"Freeze write traffic","x":280,"y":200},{"id":"n3","type":"script","label":"Promote standby cluster","x":520,"y":200},{"id":"n4","type":"script","label":"Assurance transactions","x":760,"y":200},{"id":"n5","type":"script","label":"Measure RTO / RPO","x":1000,"y":200},{"id":"n6","type":"script","label":"Fail back to primary","x":1240,"y":200},{"id":"n7","type":"script","label":"Reconcile in-flight payments","x":1480,"y":200},{"id":"n8","type":"notify","label":"Publish evidence pack","x":1720,"y":200}],"edges":[{"from":"n1","to":"n2"},{"from":"n2","to":"n3"},{"from":"n3","to":"n4"},{"from":"n4","to":"n5"},{"from":"n5","to":"n6"},{"from":"n6","to":"n7"},{"from":"n7","to":"n8"}]}',8,0,'demo-seed');

USE autoops_agent;

INSERT INTO agents (id, tenant_id, project_id, name, description, model, instructions, tools, tool_count, enabled, created_by) VALUES
(9301,'intertec-systems-0c600f88',9001,'Banking Ops Copilot','On-call assistant for the payments and core banking night shift. Explains what broke and what to do, and can trigger pre-approved remediation only.','claude-sonnet-4','You assist the night-shift banking operations team. You may explain failures, correlate breaks across the payment hub, nostro and ledger, and rerun allowlisted jobs. You must never post financial entries, unblock a card or release a payment - those require a human approval gate. Every action you take is written to the immutable audit log.','["AutoOps run history","Runbook knowledge base","Rerun (allowlisted jobs)","Slack notify"]',4,1,'demo-seed'),
(9302,'intertec-systems-0c600f88',9001,'Compliance Research Analyst','Answers regulatory and internal-policy questions with citations, and pre-fills evidence packs for audit requests. Read-only by design.','claude-opus-4','You answer regulatory and internal policy questions for the compliance team. Every answer must cite a source circular or policy document. You are read-only: you never file, submit or attest to anything with the regulator. If the knowledge base does not cover a question, say so plainly rather than inferring an answer.','["Circular + policy knowledge base","Compliance report search","Audit log search"]',3,1,'demo-seed');
