-- An agent can now RUN, and a person can stop one. Both belong in the audit
-- trail: an agent run is the point where a model's decision becomes a change
-- on a customer's infrastructure, and "who set that off" has to be answerable.
--
-- Full list restated because MySQL has no "add value" for ENUM. Order is
-- preserved and only the two AGENT_RUN_* values are new, so every stored row
-- keeps the value it had.
ALTER TABLE core_audit_log
    MODIFY COLUMN event_type ENUM('PROJECT_CREATED',
                            'PROJECT_UPDATED',
                            'PROJECT_ARCHIVED',
                            'PROJECT_RESTORED',
                            'WORKFLOW_CREATED',
                            'WORKFLOW_UPDATED',
                            'WORKFLOW_DELETED',
                            'WORKFLOW_ENABLED',
                            'WORKFLOW_DISABLED',
                            'JOB_CREATED',
                            'JOB_UPDATED',
                            'JOB_DELETED',
                            'AGENT_CREATED',
                            'AGENT_UPDATED',
                            'AGENT_DELETED',
                            'AGENT_ENABLED',
                            'AGENT_DISABLED',
                            'RUN_TRIGGERED',
                            'RUN_CANCELED',
                            'APPROVAL_REQUESTED',
                            'APPROVAL_APPROVED',
                            'APPROVAL_REJECTED',
                            'CONNECTION_CREATED',
                            'CONNECTION_CREDENTIALS_UPDATED',
                            'CONNECTION_VERIFIED',
                            'CONNECTION_DISCONNECTED',
                            'CONNECTION_ASSIGNED',
                            'CONNECTION_CLAIM_REJECTED',
                            'CONNECTION_QUARANTINED',
                            'SCM_CONFIGURED',
                            'SCM_EXPORTED',
                            'SCM_IMPORTED',
                            'APPROVAL_SETTINGS_UPDATED',
                            'GOVERNANCE_POLICY_UPDATED',
                            'COMPLIANCE_REPORT_GENERATED',
                            'SECRET_CREATED',
                            'SECRET_UPDATED',
                            'SECRET_DELETED',
                            'WEBHOOK_CREATED',
                            'WEBHOOK_UPDATED',
                            'WEBHOOK_DELETED',
                            'COMMAND_DISPATCHED',
                            'CONNECTOR_CREATED',
                            'CONNECTOR_DELETED',
                            'LIBRARY_CREATED',
                            'LIBRARY_CLONED',
                            'LIBRARY_UPDATED',
                            'BROADCAST_SENT',
                            'TEMPLATE_ROLLED_OUT',
                            'TEMPLATE_REVOKED',
                            'MODEL_PROVIDER_CREATED',
                            'MODEL_PROVIDER_UPDATED',
                            'MODEL_PROVIDER_DELETED',
                            'MODEL_PROVIDER_VERIFIED',
                            'AGENT_RUN_STARTED',
                            'AGENT_RUN_CANCELLED') NOT NULL;
